
RegExp.escape=function(s){return s.replace(/[-\/\\^$*+?.()|[\]{}]/g,'\\$&');};(function($){'use strict'
$.csv={defaults:{separator:',',delimiter:'"',headers:true},hooks:{castToScalar:function(value,state){var hasDot=/\./;if(isNaN(value)){return value;}else{if(hasDot.test(value)){return parseFloat(value);}else{var integer=parseInt(value);if(isNaN(integer)){return null;}else{return integer;}}}}},parsers:{parse:function(csv,options){var separator=options.separator;var delimiter=options.delimiter;if(!options.state.rowNum){options.state.rowNum=1;}
if(!options.state.colNum){options.state.colNum=1;}
var data=[];var entry=[];var state=0;var value=''
var exit=false;function endOfEntry(){state=0;value='';if(options.start&&options.state.rowNum<options.start){entry=[];options.state.rowNum++;options.state.colNum=1;return;}
if(options.onParseEntry===undefined){data.push(entry);}else{var hookVal=options.onParseEntry(entry,options.state);if(hookVal!==false){data.push(hookVal);}}
entry=[];if(options.end&&options.state.rowNum>=options.end){exit=true;}
options.state.rowNum++;options.state.colNum=1;}
function endOfValue(){if(options.onParseValue===undefined){entry.push(value);}else{var hook=options.onParseValue(value,options.state);if(hook!==false){entry.push(hook);}}
value='';state=0;options.state.colNum++;}
var escSeparator=RegExp.escape(separator);var escDelimiter=RegExp.escape(delimiter);var match=/(D|S|\n|\r|[^DS\r\n]+)/;var matchSrc=match.source;matchSrc=matchSrc.replace(/S/g,escSeparator);matchSrc=matchSrc.replace(/D/g,escDelimiter);match=RegExp(matchSrc,'gm');csv.replace(match,function(m0){if(exit){return;}
switch(state){case 0:if(m0===separator){value+='';endOfValue();break;}
if(m0===delimiter){state=1;break;}
if(m0==='\n'){endOfValue();endOfEntry();break;}
if(/^\r$/.test(m0)){break;}
value+=m0;state=3;break;case 1:if(m0===delimiter){state=2;break;}
value+=m0;state=1;break;case 2:if(m0===delimiter){value+=m0;state=1;break;}
if(m0===separator){endOfValue();break;}
if(m0==='\n'){endOfValue();endOfEntry();break;}
if(/^\r$/.test(m0)){break;}
throw new Error('CSVDataError: Illegal State [Row:'+options.state.rowNum+'][Col:'+options.state.colNum+']');case 3:if(m0===separator){endOfValue();break;}
if(m0==='\n'){endOfValue();endOfEntry();break;}
if(/^\r$/.test(m0)){break;}
if(m0===delimiter){throw new Error('CSVDataError: Illegal Quote [Row:'+options.state.rowNum+'][Col:'+options.state.colNum+']');}
throw new Error('CSVDataError: Illegal Data [Row:'+options.state.rowNum+'][Col:'+options.state.colNum+']');default:throw new Error('CSVDataError: Unknown State [Row:'+options.state.rowNum+'][Col:'+options.state.colNum+']');}});if(entry.length!==0){endOfValue();endOfEntry();}
return data;},splitLines:function(csv,options){var separator=options.separator;var delimiter=options.delimiter;if(!options.state.rowNum){options.state.rowNum=1;}
var entries=[];var state=0;var entry='';var exit=false;function endOfLine(){state=0;if(options.start&&options.state.rowNum<options.start){entry='';options.state.rowNum++;return;}
if(options.onParseEntry===undefined){entries.push(entry);}else{var hookVal=options.onParseEntry(entry,options.state);if(hookVal!==false){entries.push(hookVal);}}
entry='';if(options.end&&options.state.rowNum>=options.end){exit=true;}
options.state.rowNum++;}
var escSeparator=RegExp.escape(separator);var escDelimiter=RegExp.escape(delimiter);var match=/(D|S|\n|\r|[^DS\r\n]+)/;var matchSrc=match.source;matchSrc=matchSrc.replace(/S/g,escSeparator);matchSrc=matchSrc.replace(/D/g,escDelimiter);match=RegExp(matchSrc,'gm');csv.replace(match,function(m0){if(exit){return;}
switch(state){case 0:if(m0===separator){entry+=m0;state=0;break;}
if(m0===delimiter){entry+=m0;state=1;break;}
if(m0==='\n'){endOfLine();break;}
if(/^\r$/.test(m0)){break;}
entry+=m0;state=3;break;case 1:if(m0===delimiter){entry+=m0;state=2;break;}
entry+=m0;state=1;break;case 2:var prevChar=entry.substr(entry.length-1);if(m0===delimiter&&prevChar===delimiter){entry+=m0;state=1;break;}
if(m0===separator){entry+=m0;state=0;break;}
if(m0==='\n'){endOfLine();break;}
if(m0==='\r'){break;}
throw new Error('CSVDataError: Illegal state [Row:'+options.state.rowNum+']');case 3:if(m0===separator){entry+=m0;state=0;break;}
if(m0==='\n'){endOfLine();break;}
if(m0==='\r'){break;}
if(m0===delimiter){throw new Error('CSVDataError: Illegal quote [Row:'+options.state.rowNum+']');}
throw new Error('CSVDataError: Illegal state [Row:'+options.state.rowNum+']');default:throw new Error('CSVDataError: Unknown state [Row:'+options.state.rowNum+']');}});if(entry!==''){endOfLine();}
return entries;},parseEntry:function(csv,options){var separator=options.separator;var delimiter=options.delimiter;if(!options.state.rowNum){options.state.rowNum=1;}
if(!options.state.colNum){options.state.colNum=1;}
var entry=[];var state=0;var value='';function endOfValue(){if(options.onParseValue===undefined){entry.push(value);}else{var hook=options.onParseValue(value,options.state);if(hook!==false){entry.push(hook);}}
value='';state=0;options.state.colNum++;}
if(!options.match){var escSeparator=RegExp.escape(separator);var escDelimiter=RegExp.escape(delimiter);var match=/(D|S|\n|\r|[^DS\r\n]+)/;var matchSrc=match.source;matchSrc=matchSrc.replace(/S/g,escSeparator);matchSrc=matchSrc.replace(/D/g,escDelimiter);options.match=RegExp(matchSrc,'gm');}
csv.replace(options.match,function(m0){switch(state){case 0:if(m0===separator){value+='';endOfValue();break;}
if(m0===delimiter){state=1;break;}
if(m0==='\n'||m0==='\r'){break;}
value+=m0;state=3;break;case 1:if(m0===delimiter){state=2;break;}
value+=m0;state=1;break;case 2:if(m0===delimiter){value+=m0;state=1;break;}
if(m0===separator){endOfValue();break;}
if(m0==='\n'||m0==='\r'){break;}
throw new Error('CSVDataError: Illegal State [Row:'+options.state.rowNum+'][Col:'+options.state.colNum+']');case 3:if(m0===separator){endOfValue();break;}
if(m0==='\n'||m0==='\r'){break;}
if(m0===delimiter){throw new Error('CSVDataError: Illegal Quote [Row:'+options.state.rowNum+'][Col:'+options.state.colNum+']');}
throw new Error('CSVDataError: Illegal Data [Row:'+options.state.rowNum+'][Col:'+options.state.colNum+']');default:throw new Error('CSVDataError: Unknown State [Row:'+options.state.rowNum+'][Col:'+options.state.colNum+']');}});endOfValue();return entry;}},toArray:function(csv,options,callback){var options=(options!==undefined?options:{});var config={};config.callback=((callback!==undefined&&typeof(callback)==='function')?callback:false);config.separator='separator'in options?options.separator:$.csv.defaults.separator;config.delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;var state=(options.state!==undefined?options.state:{});var options={delimiter:config.delimiter,separator:config.separator,onParseEntry:options.onParseEntry,onParseValue:options.onParseValue,state:state}
var entry=$.csv.parsers.parseEntry(csv,options);if(!config.callback){return entry;}else{config.callback('',entry);}},toArrays:function(csv,options,callback){var options=(options!==undefined?options:{});var config={};config.callback=((callback!==undefined&&typeof(callback)==='function')?callback:false);config.separator='separator'in options?options.separator:$.csv.defaults.separator;config.delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;var data=[];var options={delimiter:config.delimiter,separator:config.separator,onParseEntry:options.onParseEntry,onParseValue:options.onParseValue,start:options.start,end:options.end,state:{rowNum:1,colNum:1}};data=$.csv.parsers.parse(csv,options);if(!config.callback){return data;}else{config.callback('',data);}},toObjects:function(csv,options,callback){var options=(options!==undefined?options:{});var config={};config.callback=((callback!==undefined&&typeof(callback)==='function')?callback:false);config.separator='separator'in options?options.separator:$.csv.defaults.separator;config.delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;config.headers='headers'in options?options.headers:$.csv.defaults.headers;options.start='start'in options?options.start:1;if(config.headers){options.start++;}
if(options.end&&config.headers){options.end++;}
var lines=[];var data=[];var options={delimiter:config.delimiter,separator:config.separator,onParseEntry:options.onParseEntry,onParseValue:options.onParseValue,start:options.start,end:options.end,state:{rowNum:1,colNum:1},match:false};var headerOptions={delimiter:config.delimiter,separator:config.separator,start:1,end:1,state:{rowNum:1,colNum:1}}
var headerLine=$.csv.parsers.splitLines(csv,headerOptions);var headers=$.csv.toArray(headerLine[0],options);var lines=$.csv.parsers.splitLines(csv,options);options.state.colNum=1;if(headers){options.state.rowNum=2;}else{options.state.rowNum=1;}
for(var i=0,len=lines.length;i<len;i++){var entry=$.csv.toArray(lines[i],options);var object={};for(var j in headers){object[headers[j]]=entry[j];}
data.push(object);options.state.rowNum++;}
if(!config.callback){return data;}else{config.callback('',data);}},fromArrays:function(arrays,options,callback){var options=(options!==undefined?options:{});var config={};config.callback=((callback!==undefined&&typeof(callback)==='function')?callback:false);config.separator='separator'in options?options.separator:$.csv.defaults.separator;config.delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;config.escaper='escaper'in options?options.escaper:$.csv.defaults.escaper;config.experimental='experimental'in options?options.experimental:false;if(!config.experimental){throw new Error('not implemented');}
var output=[];for(i in arrays){output.push(arrays[i]);}
if(!config.callback){return output;}else{config.callback('',output);}},fromObjects2CSV:function(objects,options,callback){var options=(options!==undefined?options:{});var config={};config.callback=((callback!==undefined&&typeof(callback)==='function')?callback:false);config.separator='separator'in options?options.separator:$.csv.defaults.separator;config.delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;config.experimental='experimental'in options?options.experimental:false;if(!config.experimental){throw new Error('not implemented');}
var output=[];for(i in objects){output.push(arrays[i]);}
if(!config.callback){return output;}else{config.callback('',output);}}};$.csvEntry2Array=$.csv.toArray;$.csv2Array=$.csv.toArrays;$.csv2Dictionary=$.csv.toObjects;})(jQuery);/*!
 * FooTable - Awesome Responsive Tables
 * Version : 2.0.1.2
 * http://fooplugins.com/plugins/footable-jquery/
 *
 * Requires jQuery - http://jquery.com/
 *
 * Copyright 2013 Steven Usher & Brad Vincent
 * Released under the MIT license
 * You are free to use FooTable in commercial projects as long as this copyright header is left intact.
 *
 * Date: 21 Sep 2013
 */
(function(f,l,u){function r(){var b=this;b.id=null;b.busy=!1;b.start=function(f,h){b.busy||(b.stop(),b.id=setTimeout(function(){f();b.id=null;b.busy=!1},h),b.busy=!0)};b.stop=function(){null!==b.id&&(clearTimeout(b.id),b.id=null,b.busy=!1)}}function t(b,g,h){var a=this;a.id=h;a.table=b;a.options=g;a.breakpoints=[];a.breakpointNames="";a.columns={};a.plugins=l.footable.plugins.load(a);var m=a.options,d=m.classes,p=m.events,k=m.triggers,q=0;a.timers={resize:new r,register:function(c){a.timers[c]=new r;
return a.timers[c]}};a.init=function(){var c=f(l),e=f(a.table);l.footable.plugins.init(a);if(e.hasClass(d.loaded))a.raise(p.alreadyInitialized);else{a.raise(p.initializing);e.addClass(d.loading);e.find(m.columnDataSelector).each(function(){var c=a.getColumnData(this);a.columns[c.index]=c});for(var b in m.breakpoints)a.breakpoints.push({name:b,width:m.breakpoints[b]}),a.breakpointNames+=b+" ";a.breakpoints.sort(function(a,c){return a.width-c.width});e.unbind(k.initialize).bind(k.initialize,function(){e.removeData("footable_info");
e.data("breakpoint","");e.trigger(k.resize);e.removeClass(d.loading);e.addClass(d.loaded).addClass(d.main);a.raise(p.initialized)}).unbind(k.redraw).bind(k.redraw,function(){a.redraw()}).unbind(k.resize).bind(k.resize,function(){a.resize()}).unbind(k.expandFirstRow).bind(k.expandFirstRow,function(){e.find(m.toggleSelector).first().not("."+d.detailShow).trigger(k.toggleRow)}).unbind(k.expandAll).bind(k.expandAll,function(){e.find(m.toggleSelector).not("."+d.detailShow).trigger(k.toggleRow)}).unbind(k.collapseAll).bind(k.collapseAll,
function(){e.find("."+d.detailShow).trigger(k.toggleRow)});e.trigger(k.initialize);c.bind("resize.footable",function(){a.timers.resize.stop();a.timers.resize.start(function(){a.raise(k.resize)},m.delay)})}};a.addRowToggle=function(){if(m.addRowToggle){var c=f(a.table);c.find("span."+d.toggle).remove();for(var e in a.columns){var b=a.columns[e];if(b.toggle){e="\x3e tbody \x3e tr:not(."+d.detail+",."+d.disabled+") \x3e td:nth-child("+(parseInt(b.index,10)+1)+")";c.find(e).not("."+d.detailCell).append(f(m.toggleHTMLElement).addClass(d.toggle));
return}}c.find("\x3e tbody \x3e tr:not(."+d.detail+",."+d.disabled+") \x3e td:first-child").not("."+d.detailCell).append(f(m.toggleHTMLElement).addClass(d.toggle))}};a.setColumnClasses=function(){$table=f(a.table);for(var c in a.columns){var e=a.columns[c];if(null!==e.className){var b="",n=!0;f.each(e.matches,function(a,c){n||(b+=", ");b+="\x3e tbody \x3e tr:not(."+d.detail+") \x3e td:nth-child("+(parseInt(c,10)+1)+")";n=!1});$table.find(b).not("."+d.detailCell).addClass(e.className)}}};a.bindToggleSelectors=
function(){var c=f(a.table);a.hasAnyBreakpointColumn()&&(c.find(m.toggleSelector).unbind(k.toggleRow).bind(k.toggleRow,function(c){c=f(this).is("tr")?f(this):f(this).parents("tr:first");a.toggleDetail(c)}),c.find(m.toggleSelector).unbind("click.footable").bind("click.footable",function(a){c.is(".breakpoint")&&f(a.target).is("td,."+d.toggle)&&f(this).trigger(k.toggleRow)}))};a.parse=function(a,e){return(m.parsers[e.type]||m.parsers.alpha)(a)};a.getColumnData=function(c){var e=f(c),b=e.data("hide"),
n=e.index(),b=jQuery.map((b||"").split(","),function(a){return jQuery.trim(a)}),n={index:n,hide:{},type:e.data("type")||"alpha",name:e.data("name")||f.trim(e.text()),ignore:e.data("ignore")||!1,toggle:e.data("toggle")||!1,className:e.data("class")||null,matches:[],names:{},group:e.data("group")||null,groupName:null};if(null!==n.group){var d=f(a.table).find('\x3e thead \x3e tr.footable-group-row \x3e th[data-group\x3d"'+n.group+'"], \x3e thead \x3e tr.footable-group-row \x3e td[data-group\x3d"'+n.group+
'"]').first();n.groupName=a.parse(d,{type:"alpha"})}d=parseInt(e.prev().attr("colspan")||0,10);q+=1<d?d-1:0;var d=parseInt(e.attr("colspan")||0,10),g=n.index+q;if(1<d)for(var h=e.data("names"),h=(h||"").split(","),k=0;k<d;k++)n.matches.push(k+g),k<h.length&&(n.names[k+g]=h[k]);else n.matches.push(g);n.hide["default"]="all"===e.data("hide")||0<=f.inArray("default",b);var d=!1,l;for(l in m.breakpoints)n.hide[l]="all"===e.data("hide")||0<=f.inArray(l,b),d=d||n.hide[l];n.hasBreakpoint=d;return a.raise(p.columnData,
{column:{data:n,th:c}}).column.data};a.getViewportWidth=function(){return window.innerWidth||(document.body?document.body.offsetWidth:0)};a.calculateWidth=function(a,e){if(jQuery.isFunction(m.calculateWidthOverride))return m.calculateWidthOverride(a,e);e.viewportWidth<e.width&&(e.width=e.viewportWidth);e.parentWidth<e.width&&(e.width=e.parentWidth);return e};a.hasBreakpointColumn=function(c){for(var e in a.columns)if(a.columns[e].hide[c]&&!a.columns[e].ignore)return!0;return!1};a.hasAnyBreakpointColumn=
function(){for(var c in a.columns)if(a.columns[c].hasBreakpoint)return!0;return!1};a.resize=function(){if(a.hasAnyBreakpointColumn()){var c=f(a.table);if(c.is(":visible")){var e={width:c.width(),viewportWidth:a.getViewportWidth(),parentWidth:c.parent().width()},e=a.calculateWidth(c,e),b=c.data("footable_info");c.data("footable_info",e);a.raise(p.resizing,{old:b,info:e});if(!b||b&&b.width&&b.width!==e.width){for(var d=null,g,h=0;h<a.breakpoints.length;h++)if((g=a.breakpoints[h])&&g.width&&e.width<=
g.width){d=g;break}d=null===d?"default":d.name;g=a.hasBreakpointColumn(d);h=c.data("breakpoint");c.data("breakpoint",d).removeClass("default breakpoint").removeClass(a.breakpointNames).addClass(d+(g?" breakpoint":""));d!==h&&(c.trigger(k.redraw),a.raise(p.breakpoint,{breakpoint:d,info:e}))}a.raise(p.resized,{old:b,info:e})}}};a.redraw=function(){a.addRowToggle();a.bindToggleSelectors();a.setColumnClasses();var c=f(a.table),b=c.data("breakpoint"),g=a.hasBreakpointColumn(b);c.find("\x3e tbody \x3e tr:not(."+
d.detail+")").data("detail_created",!1).end().find("\x3e thead \x3e tr:last-child \x3e th").each(function(){var g=a.columns[f(this).index()],h="",k=!0;f.each(g.matches,function(a,c){k||(h+=", ");var b=c+1;h+="\x3e tbody \x3e tr:not(."+d.detail+") \x3e td:nth-child("+b+")";h+=", \x3e tfoot \x3e tr:not(."+d.detail+") \x3e td:nth-child("+b+")";h+=", \x3e colgroup \x3e col:nth-child("+b+")";k=!1});var h=h+(', \x3e thead \x3e tr[data-group-row\x3d"true"] \x3e th[data-group\x3d"'+g.group+'"]'),m=c.find(h).add(this);
!1===g.hide[b]?m.show():m.hide();if(1===c.find("\x3e thead \x3e tr.footable-group-row").length){var m=c.find('\x3e thead \x3e tr:last-child \x3e th[data-group\x3d"'+g.group+'"]:visible, \x3e thead \x3e tr:last-child \x3e th[data-group\x3d"'+g.group+'"]:visible'),g=c.find('\x3e thead \x3e tr.footable-group-row \x3e th[data-group\x3d"'+g.group+'"], \x3e thead \x3e tr.footable-group-row \x3e td[data-group\x3d"'+g.group+'"]'),l=0;f.each(m,function(){l+=parseInt(f(this).attr("colspan")||1,10)});0<l?g.attr("colspan",
l).show():g.hide()}}).end().find("\x3e tbody \x3e tr."+d.detailShow).each(function(){a.createOrUpdateDetailRow(this)});c.find("\x3e tbody \x3e tr."+d.detailShow+":visible").each(function(){var a=f(this).next();a.hasClass(d.detail)&&(g?a.show():a.hide())});c.find("\x3e thead \x3e tr \x3e th.footable-last-column, \x3e tbody \x3e tr \x3e td.footable-last-column").removeClass("footable-last-column");c.find("\x3e thead \x3e tr \x3e th.footable-first-column, \x3e tbody \x3e tr \x3e td.footable-first-column").removeClass("footable-first-column");
c.find("\x3e thead \x3e tr, \x3e tbody \x3e tr").find("\x3e th:visible:last, \x3e td:visible:last").addClass("footable-last-column").end().find("\x3e th:visible:first, \x3e td:visible:first").addClass("footable-first-column");a.raise(p.redrawn)};a.toggleDetail=function(c){c=c.jquery?c:f(c);var b=c.next();c.hasClass(d.detailShow)?(c.removeClass(d.detailShow),b.hasClass(d.detail)&&b.hide(),a.raise(p.rowCollapsed,{row:c[0]})):(a.createOrUpdateDetailRow(c[0]),c.addClass(d.detailShow).next().show(),a.raise(p.rowExpanded,
{row:c[0]}))};a.removeRow=function(c){c=c.jquery?c:f(c);c.hasClass(d.detail)&&(c=c.prev());var b=c.next();!0===c.data("detail_created")&&b.remove();c.remove();a.raise(p.rowRemoved)};a.appendRow=function(c){c=c.jquery?c:f(c);f(a.table).find("tbody").append(c);a.redraw()};a.getColumnFromTdIndex=function(c){var b=null,d;for(d in a.columns)if(0<=f.inArray(c,a.columns[d].matches)){b=a.columns[d];break}return b};a.createOrUpdateDetailRow=function(b){b=f(b);var e=b.next(),g,h=[];if(!0===b.data("detail_created"))return!0;
if(b.is(":hidden"))return!1;a.raise(p.rowDetailUpdating,{row:b,detail:e});b.find("\x3e td:hidden").each(function(){var b=f(this).index(),c=a.getColumnFromTdIndex(b),d=c.name;if(!0===c.ignore)return!0;b in c.names&&(d=c.names[b]);h.push({name:d,value:a.parse(this,c),display:f.trim(f(this).html()),group:c.group,groupName:c.groupName});return!0});if(0===h.length)return!1;g=b.find("\x3e td:visible").length;var k=e.hasClass(d.detail);k||(e=f('\x3ctr class\x3d"'+d.detail+'"\x3e\x3ctd class\x3d"'+d.detailCell+
'"\x3e\x3cdiv class\x3d"'+d.detailInner+'"\x3e\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e'),b.after(e));e.find("\x3e td:first").attr("colspan",g);g=e.find("."+d.detailInner).empty();m.createDetail(g,h,m.createGroupedDetail,m.detailSeparator,d);b.data("detail_created",!0);a.raise(p.rowDetailUpdated,{row:b,detail:e});return!k};a.raise=function(b,d){!0===a.options.debug&&f.isFunction(a.options.log)&&a.options.log(b,"event");d=d||{};var g={ft:a};f.extend(!0,g,d);var h=f.Event(b,g);h.ft||f.extend(!0,h,g);f(a.table).trigger(h);
return h};a.reset=function(){var b=f(a.table);b.removeData("footable_info").data("breakpoint","").removeClass(d.loading).removeClass(d.loaded);b.find(m.toggleSelector).unbind(k.toggleRow).unbind("click.footable");b.find("\x3e tbody \x3e tr").removeClass(d.detailShow);b.find("\x3e tbody \x3e tr."+d.detail).remove();a.raise(p.reset)};a.init();return a}l.footable={options:{delay:100,breakpoints:{phone:480,tablet:1024},parsers:{alpha:function(b){return f(b).data("value")||f.trim(f(b).text())},numeric:function(b){b=
f(b).data("value")||f(b).text().replace(/[^0-9.\-]/g,"");b=parseFloat(b);isNaN(b)&&(b=0);return b}},addRowToggle:!0,calculateWidthOverride:null,toggleSelector:" \x3e tbody \x3e tr:not(.footable-row-detail)",columnDataSelector:"\x3e thead \x3e tr:last-child \x3e th, \x3e thead \x3e tr:last-child \x3e td",detailSeparator:":",toggleHTMLElement:"\x3cspan /\x3e",createGroupedDetail:function(b){for(var g={_none:{name:null,data:[]}},h=0;h<b.length;h++){var a=b[h].group;null!==a?(a in g||(g[a]={name:b[h].groupName||
b[h].group,data:[]}),g[a].data.push(b[h])):g._none.data.push(b[h])}return g},createDetail:function(b,g,h,a,f){g=h(g);for(var d in g)if(0!==g[d].data.length){"_none"!==d&&b.append('\x3cdiv class\x3d"'+f.detailInnerGroup+'"\x3e'+g[d].name+"\x3c/div\x3e");h="";h+='\x3ctable class\x3d"detailsTable"\x3e';for(var l=0;l<g[d].data.length;l++)h+='\x3ctr\x3e\x3ctd class\x3d"'+f.detailInnerName+'"\x3e'+g[d].data[l].name+(g[d].data[l].name?a:"")+'\x3c/td\x3e\x3ctd class\x3d"'+f.detailInnerValue+'"\x3e'+g[d].data[l].display+
"\x3c/td\x3e\x3c/tr\x3e";h+="\x3c/table\x3e";b.append(h)}},classes:{main:"footable",loading:"footable-loading",loaded:"footable-loaded",toggle:"footable-toggle",disabled:"footable-disabled",detail:"footable-row-detail",detailCell:"footable-row-detail-cell",detailInner:"footable-row-detail-inner",detailInnerRow:"footable-row-detail-row",detailInnerGroup:"footable-row-detail-group",detailInnerName:"footable-row-detail-name",detailInnerValue:"footable-row-detail-value",detailShow:"footable-detail-show"},
triggers:{initialize:"footable_initialize",resize:"footable_resize",redraw:"footable_redraw",toggleRow:"footable_toggle_row",expandFirstRow:"footable_expand_first_row",expandAll:"footable_expand_all",collapseAll:"footable_collapse_all"},events:{alreadyInitialized:"footable_already_initialized",initializing:"footable_initializing",initialized:"footable_initialized",resizing:"footable_resizing",resized:"footable_resized",redrawn:"footable_redrawn",breakpoint:"footable_breakpoint",columnData:"footable_column_data",
rowDetailUpdating:"footable_row_detail_updating",rowDetailUpdated:"footable_row_detail_updated",rowCollapsed:"footable_row_collapsed",rowExpanded:"footable_row_expanded",rowRemoved:"footable_row_removed",reset:"footable_reset"},debug:!1,log:null},version:{major:0,minor:5,toString:function(){return l.footable.version.major+"."+l.footable.version.minor},parse:function(b){version=/(\d+)\.?(\d+)?\.?(\d+)?/.exec(b);return{major:parseInt(version[1],10)||0,minor:parseInt(version[2],10)||0,patch:parseInt(version[3],
10)||0}}},plugins:{_validate:function(b){if(!f.isFunction(b))return!0===l.footable.options.debug&&console.error('Validation failed, expected type "function", received type "{0}".',typeof b),!1;b=new b;if("string"!==typeof b.name)return!0===l.footable.options.debug&&console.error('Validation failed, plugin does not implement a string property called "name".',b),!1;if(!f.isFunction(b.init))return!0===l.footable.options.debug&&console.error('Validation failed, plugin "'+b.name+'" does not implement a function called "init".',
b),!1;!0===l.footable.options.debug&&console.log('Validation succeeded for plugin "'+b.name+'".',b);return!0},registered:[],register:function(b,g){l.footable.plugins._validate(b)&&(l.footable.plugins.registered.push(b),"object"===typeof g&&f.extend(!0,l.footable.options,g))},load:function(b){var g=[],h,a;for(a=0;a<l.footable.plugins.registered.length;a++)try{h=l.footable.plugins.registered[a],g.push(new h(b))}catch(f){!0===l.footable.options.debug&&console.error(f)}return g},init:function(b){for(var g=
0;g<b.plugins.length;g++)try{b.plugins[g].init(b)}catch(f){!0===l.footable.options.debug&&console.error(f)}}}};var s=0;f.fn.footable=function(b){b=b||{};var g=f.extend(!0,{},l.footable.options,b);return this.each(function(){s++;var b=new t(this,g,s);f(this).data("footable",b)})}})(jQuery,window);var spreadSheetParams={sortable:!0,showHeaderFooter:!0,appHeight:"autoMobile",filter:!0,paginate:!1,pageSize:5,ignoreColumns:[],hideAllColumns:[],hidePhoneColumns:[],hidePhoneTabletColumns:[]};
function SpreadSheet(){function t(){$("#chartTableDiv").show();$("#pagerFilter").show();!1===spreadSheetParams.showHeaderFooter?($("#filterTable").hide(),$("#pagerFilter").hide()):spreadSheetParams.paginate&&"mobile"!=k&&($("#theTable").data("page-navigation",".pagination"),spreadSheetParams.pageSize&&$("#theTable").data("page-size",spreadSheetParams.pageSize));dataLoader.loadCsv(D)}function D(a){E(a);var c=$("#theTable");c.footable();f(c,spreadSheetParams.columns,spreadSheetParams.columnsOnOff,!0);
F(spreadSheetParams);c.bind("footable_paging",function(){f(c,spreadSheetParams.columns,spreadSheetParams.columnsOnOff,!1)});c.bind("footable_resized",function(){f(c,spreadSheetParams.columns,spreadSheetParams.columnsOnOff,!1)});c.bind("footable_row_collapsed",function(){f(c,spreadSheetParams.columns,spreadSheetParams.columnsOnOff,!1)});c.bind("footable_row_expanded",function(){f(c,spreadSheetParams.columns,spreadSheetParams.columnsOnOff,!1)});c.bind("footable_filtered",function(){v();f(c,spreadSheetParams.columns,
spreadSheetParams.columnsOnOff,!1)});c.bind("footable_sorted",function(){v()});$(window).resize(function(){f(c,spreadSheetParams.columns,spreadSheetParams.columnsOnOff,!1)});spreadSheetParams.isError&&w(5)}function w(a){if(!(0>=a)){$("span.footable-sort-indicator").hide();var c=$(".footableOdd").css("backgroundColor");$("#theTable th").css("height","70px").css("vertical-align","bottom");$("#theTable th").css("backgroundColor",c);$("#theTable td").css("height","70px");$("#theTable td").css("borderTop",
"none");$(".footable\x3etbody\x3etr").hover(function(){$(this).css("backgroundColor",c)});setTimeout(function(){w(a-1)},30)}}function v(){$(".footable\x3etbody\x3etr:not(.footable-row-detail-cell)").removeClass("footableEven").removeClass("footableOdd");var a=!0;$.each($(".footable\x3etbody").children(),function(){!$(this).hasClass("footable-row-detail")&&!$(this).hasClass("footable-filtered")&&(a?($(this).addClass("footableOdd"),a=!1):($(this).addClass("footableEven"),a=!0))})}function f(a,c,d,b){d||
(c=0);d=c;"mobile"===k&&("scrolling"===spreadSheetParams.mobileView&&2<q)&&(d=1.5);c=0!=d&&d<q;"mobile"===k&&"scrolling"!==spreadSheetParams.mobileView&&(c=!1);var e="auto"==spreadSheetParams.appHeight||"mobile"==k;("mobile"!=k||"scrolling"==spreadSheetParams.mobileView)&&G(a,d,u(),e,k,c);e?(d=a.outerHeight(!0),c&&(d+=10),0===m&&!0===spreadSheetParams.showHeaderFooter&&(m=$("#filterTable").outerHeight(!0)+$("#pagerFilter").outerHeight(!0)),Wix.setHeight(d+m+A())):0===s&&(s=u()-A(),$("#tableWrapper").css("max-height",
s));!0===b&&(setTimeout(function(){f(a,spreadSheetParams.columns,spreadSheetParams.columnsOnOff,!1)},10),setTimeout(function(){f(a,spreadSheetParams.columns,spreadSheetParams.columnsOnOff,!1)},100),setTimeout(function(){f(a,spreadSheetParams.columns,spreadSheetParams.columnsOnOff,!1)},1E3))}function u(){var a=void 0;0===m&&!0===spreadSheetParams.showHeaderFooter&&(m=$("#filterTable").outerHeight(!0)+$("#pagerFilter").outerHeight(!0));a=n&&n.rect&&n.rect.height?n.rect.height:$(window).height();return a-
m}function A(){var a=$("body").css("border-top-width");0<a.indexOf("px")?(a=a.substring(0,a.indexOf("px")),a*=2):a=0;return a}function G(a,c,d,b,e,k){if(0!=c&&q>c){var l=a.outerHeight(!0);k&&(l+=10);d=l>d&&!b;e="mobile"===e?Wix.Utils.getWidth():$(window).width();d&&(e-=10);var f=e/c;a.css("width",f*q);$.each(a.find("th"),function(){$(this).css("width",f);$(this).css("min-width",f)})}}function H(a){$.ajaxSetup({cache:!0});var c=[];spreadSheetParams.sortable&&("mobile"!=k||"scrolling"==spreadSheetParams.mobileView)&&
c.push($.getScript("../static/js/foo/js/footable.sort.js?v\x3d"+a));spreadSheetParams.filter&&c.push($.getScript("../static/js/foo/js/footable.filter.js?v\x3d"+a));spreadSheetParams.paginate&&"mobile"!=k&&c.push($.getScript("../static/js/foo/js/footable.paginate.js?v\x3d"+a));return c}function E(a){var c={separator:",",delimiter:'"',start:1,state:{rowNum:1,colNum:1},match:!1};try{var d=$.csv.parsers.splitLines(a,c)}catch(b){pageManager.showCsvError();return}if(spreadSheetParams.filter){a=$("#theTable");
var c=$("#filterBox"),f=$("#filterInput");c.show();a.data("filter","#filterInput");f.attr("placeholder",spreadSheetParams.filterText)}else $("#filterBox").remove();a=$.csv.toArray(d[0]);q=a.length;var c=$("\x3ctr\x3e\x3c/tr\x3e"),f=0,h;for(h in a){var l="";"mobile"==k&&("scrolling"!=spreadSheetParams.mobileView&&0<f)&&(l=' data-hide\x3d"all"');l=$("\x3cth id\x3d'thCol"+f+"'"+l+"\x3e\x3c/th\x3e");l.text(a[h]);a[h]&&(B=!1);c.append(l);f++}$("#theTable").append($("\x3cthead\x3e\x3c/thead\x3e").append(c));
B&&(e(["#theTable \x3e thead \x3e tr",".footable-row-detail-name"],"display:none;"),e(["#theTable \x3e tbody \x3e tr:first-child \x3e td"],"border-top:none;"));h=[];for(i=1;i<d.length;i++){a=$.csv.toArray(d[i]);a.length>q&&(q=a.length);var c=h,f=0,l=void 0,l=$("\x3ctr\x3e\x3c/tr\x3e"),m=void 0;for(m in a){var p=a[m],n;a:{var s=p,x=$("\x3ctd\x3e\x3c/td\x3e");try{var g=JSON.parse(s);if("complex"===g.cellType){var y=x,z="";if("webAddress"===g.type&&null!==g.href||"email"===g.type&&null!==g.email){var r=
$("\x3ca\x3e\x3c/a\x3e");if("email"===g.type)r.attr("href","mailto:"+g.email),z=g.email;else{var t=g.href.trim().toLowerCase().indexOf("javascript"),v=g.href.trim().toLowerCase().indexOf("http://"),w=g.href.trim().toLowerCase().indexOf("https://");if(0===v||0===w)r.attr("href",g.href),z=g.href;else if(0>t||3<t)r.attr("href","http://"+g.href),z="http://"+g.href}null!==g.target?r.attr("target",g.target):r.attr("target","_top");y.append(r);y=r}if(null!=g.image){var u=$("\x3cimg/\x3e");u.attr("src",g.image);
y.append(u)}if(null!=g.text){var C=$("\x3cspan/\x3e");""===g.text?C.text(z):C.text(g.text);y.append(C)}n=x;break a}}catch(A){}x.text(s);n=x}l.append(n);"alpha"!==c[f]&&(c[f]=!p.trim()||$.isNumeric(p)||$.isNumeric(p.replace(/\,/g,""))||"-"===p||"%"===p[p.length-1]&&$.isNumeric(p.substr(0,p.length-1))?"numeric":"alpha");f++}$("#theTable").append(l)}for(d=d=0;d<h.length;d++)$("#thCol"+d).attr("data-type",h[d]);spreadSheetParams.paginate&&"mobile"!=k&&($("#noPager").hide(),$("#pagerFilter").append('\x3ctfoot class\x3d"hide-if-no-paging"\x3e\x3ctr\x3e\x3ctd colspan\x3d"100%" style\x3d"text-align: center;"\x3e\x3cdiv class\x3d"pagination pagination-centered hide-if-no-paging"\x3e\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e\x3c/tfoot\x3e'))}
function F(){var a={};$.extend(a,spreadSheetParams);Wix.Styles.getStyleParams(function(c){c&&c.colors&&I(a,c.colors);if(a){a.fontSize&&"large"===a.fontSize?e([".footable",".filter"],"font-size:24px;"):a.fontSize&&"medium"===a.fontSize?e([".footable",".filter"],"font-size:18px;"):e([".footable",".filter"],"font-size:14px;");c=0;void 0!==a.outerBorderWidth&&(c=a.outerBorderWidth);e(["body"],"border-width: "+c+"px; border-style: solid;");c=1;void 0!==a.innerBorderWidth&&(c=a.innerBorderWidth);e([".footable \x3e tbody \x3e tr \x3e td,.footable \x3e thead \x3e tr \x3e th"],
"border-left-width: "+c+"px; border-top-width: "+c+"px;");!0===spreadSheetParams.showHeaderFooter?(e(["#theTable"]," border-top-width:"+c+"px; border-bottom-width:"+c+"px; border-style:solid;"),$("#theTable").addClass("isInnerColor")):e(["#theTable"]," border-top-width:0;");a.alignment?"rtl"===a.alignment?(e(["div"],"direction:rtl;"),e([".footable\x3ethead\x3etr\x3eth",".footable\x3etbody\x3etr\x3etd"],"text-align:right;"),e(["div#filterBox"],"float:left;"),e([".footable\x3ethead\x3etr\x3eth:last-child",
".footable\x3etbody\x3etr\x3etd:last-child"],"border-left:0;"),e([".footable\x3ethead\x3etr\x3eth\x3espan.footable-sort-indicator",".footable-toggle"],"float:left;"),$(".footable-toggle").addClass("flip")):("center"===a.alignment&&e([".footable\x3ethead\x3etr\x3eth",".footable\x3etbody\x3etr\x3etd"],"text-align:center;"),e([".footable\x3ethead\x3etr\x3eth:first-child",".footable\x3etbody\x3etr\x3etd:first-child"],"border-left:0;"),e([".footable\x3ethead\x3etr\x3eth\x3espan.footable-sort-indicator",
".footable-toggle"],"float:right;")):(e([".footable\x3ethead\x3etr\x3eth:first-child",".footable\x3etbody\x3etr\x3etd:first-child"],"border-left:0;"),e([".footable\x3ethead\x3etr\x3eth\x3espan.footable-sort-indicator",".footable-toggle"],"float:right;"));c=[[a.rowHeight,"height"]];var d="",b;for(b in c)c[b][0]&&(d+=c[b][1]+":"+c[b][0]+";");""!==d&&e([".footable\x3etbody\x3etr"],d);!1===a.showGradient&&(b=$(".filter\x3ethead\x3etr\x3eth").css("backgroundColor"),e([".filter\x3ethead\x3etr\x3eth",".footable\x3ethead\x3etr\x3eth",
".footable\x3ethead\x3etr\x3etd",".footable\x3etfoot\x3etr\x3eth",".footable\x3etfoot\x3etr\x3etd"],"background-image:none; background-color:"+b+";"),e([".footable\x3etfoot\x3etr\x3eth",".footable\x3etfoot\x3etr\x3etd"],"background-color:"+b+";"));a.headerHeight&&e([".footable\x3ethead\x3etr"],"height:"+a.headerHeight+";");a.expandIconStyle&&$(".footable").addClass(a.expandIconStyle);a.expandIconSize&&$(".footable").addClass(a.expandIconSize);$(".footable\x3etbody\x3etr:not(.footable-row-detail-cell):odd").addClass("footableEven");
$(".footable\x3etbody\x3etr:not(.footable-row-detail-cell):even").addClass("footableOdd");b=6;void 0!==a.radius&&(b=a.radius);"mobile"==k?(c=$("#tableWrapper").width()-10-2*b,e([".searchBox"],"width: "+c+"px;text-align:center;margin:0 "+(4+b)+"px;")):e([".searchBox"],"margin: 0 "+(5+b)+"px;");e(["body"],"-moz-border-radius: "+b+"px;-webkit-border-radius: "+b+"px;border-radius: "+b+"px;");e([".footer \x3e tfoot \x3e tr \x3e td"],"-moz-border-radius: 0 0 "+b+"px "+b+"px;-webkit-border-radius: 0 0 "+
b+"px "+b+"px;border-radius: 0 0  "+b+"px "+b+"px;");e([".footer"],"-moz-border-radius: 0 0 "+b+"px "+b+"px;-webkit-border-radius: 0 0 "+b+"px "+b+"px;border-radius: 0 0  "+b+"px "+b+"px;");e([".filter \x3e thead \x3e tr:first-child \x3e th"],"-moz-border-radius: "+b+"px "+b+"px 0 0;-webkit-border-radius: "+b+"px "+b+"px 0 0;border-radius: "+b+"px "+b+"px 0 0;");e([".filter"],"-moz-border-radius: "+b+"px "+b+"px 0 0;-webkit-border-radius: "+b+"px "+b+"px 0 0;border-radius: "+b+"px "+b+"px 0 0;");
!0!==spreadSheetParams.showHeaderFooter&&(e(["#theTable \x3e thead \x3e tr \x3e th:first-child"],"-moz-border-radius: "+b+"px 0 0 0;-webkit-border-radius: "+b+"px 0 0 0;border-radius: "+b+"px 0 0 0;"),e(["#theTable \x3e thead \x3e tr \x3e th:last-child"],"-moz-border-radius: 0 "+b+"px 0 0;-webkit-border-radius: 0 "+b+"px 0 0;border-radius: 0 "+b+"px 0 0;"),e(["#theTable \x3e tbody \x3e tr:last-child \x3e td:first-child"],"-moz-border-radius: 0 0 0 "+b+"px;-webkit-border-radius: 0 0 0 "+b+"px;border-radius: 0 0 0 "+
b+"px;"),e(["#theTable \x3e tbody \x3e tr:last-child \x3e td:last-child"],"-moz-border-radius: 0 0 "+b+"px 0;-webkit-border-radius: 0 0 "+b+"px 0;border-radius: 0 0 "+b+"px 0;"),e(["#theTable \x3e tbody \x3e tr:last-child \x3e td:only-child"],"-moz-border-radius: 0 0 "+b+"px "+b+"px;-webkit-border-radius: 0 0 "+b+"px "+b+"px;border-radius: 0 0 "+b+"px "+b+"px;"),e(["#theTable"],"-moz-border-radius: "+b+"px;-webkit-border-radius: "+b+"px;border-radius: "+b+"px;"),B&&(e(["#theTable \x3e tbody \x3e tr:first-child \x3e th:first-child"],
"-moz-border-radius: "+b+"px 0 0 0;-webkit-border-radius: "+b+"px 0 0 0;border-radius: "+b+"px 0 0 0;"),e(["#theTable \x3e tbody \x3e tr:first-child \x3e th:last-child"],"-moz-border-radius: 0 "+b+"px 0 0;-webkit-border-radius: 0 "+b+"px 0 0;border-radius: 0 "+b+"px 0 0;"),e(["#theTable \x3e tbody \x3e tr:first-child \x3e th:only-child"],"-moz-border-radius: "+b+"px "+b+"px 0 0;-webkit-border-radius: "+b+"px "+b+"px 0 0;border-radius: "+b+"px "+b+"px 0 0;")))}})}function I(a,c){$.each(c,function(c,
b){a[c]=b.value})}function e(a,c,d){d=d||document;if("object"==typeof d.styleSheets)if(""===h&&(d.styleSheets.length&&(h=d.styleSheets[d.styleSheets.length-1]),d.styleSheets.length&&(d.createStyleSheet?h=d.createStyleSheet():(d.getElementsByTagName("head")[0].appendChild(d.createElement("style")),h=d.styleSheets[d.styleSheets.length-1]))),h.addRule)for(d=0;d<a.length;++d)h.addRule(a[d],c);else h.insertRule(a.join(",")+"{"+c+"}",h.cssRules.length)}var h="",k="",q,B=!0,n=void 0,m=0,s=0;this.init=function(a,
c,d){k=c;$.extend(spreadSheetParams,a);a=H(d);Wix.getBoundingRectAndOffsets(function(a){n=a});$.when.apply($,a).then(function(){t()},function(a){t()})}};function DataLoader(){function e(b){var a=c.loaderErrorTitleCsv,d=c.loaderErrorBodyCsv;c["loaderErrorTitle"+b]&&(a=c["loaderErrorTitle"+b],d=c["loaderErrorBody"+b]);pageManager.showError(a,d)}function l(b){$.ajax({type:"GET",url:"/app/file?compId\x3d"+g+"\x26instance\x3d"+h,data:"",success:function(a){k(a,b)},error:m})}function k(b,a){b=b.replace(/&lt;/g,"\x3c");b=b.replace(/&gt;/g,"\x3e");a(b)}function m(b,a,d){a=c.loaderErrorBody;d=c.loaderErrorTitle;b&&void 0!==b&&(c["loaderErrorTitle"+b.status]&&
(d=c["loaderErrorTitle"+b.status],a=c["loaderErrorBody"+b.status]),pageManager.showError(d,a))}var f,c,h,g;this.init=function(b,a,d,e){c=a;f=b;h=d;g=e};this.loadCsv=function(b){"csvUrl"===f.type?l(function(a){0==a.indexOf("{'status':")?(a=JSON.parse(a))&&"error"===a.status&&e(a.code):0<=a.indexOf("\x3c!DOCTYPE html\x3e")&&5>a.indexOf("\x3c!DOCTYPE html\x3e")&&(0<a.indexOf("\x3ctitle\x3eGoogle Sheets - create and edit spreadsheets online, for free.\x3c/title\x3e")||0<a.indexOf("\x3ctitle\x3eSign in - Google Accounts\x3c/title\x3e"))?
e(403):b(a)}):k(f.csvString,b)}};var dataLoader;
function PageManager(){var c,a,e,f,g,h;this.origVersion;this.init=function(b,d,k,l,m,n){c=k;a=b;g=d;e=l;f=m;h=n;this.origVersion=b.origVersion?Number(b.origVersion):1;!b.data||"csvUrl"===b.data.type&&!b.data.csvUrl||"csvString"===b.data.type&&!b.data.csvString?pageManager.showError(c.loaderErrorTitleEmpty,c.loaderErrorBodyEmpty):(dataLoader=new DataLoader,dataLoader.init(b.data,k,l,m),(new SpreadSheet).init(b.tableParams,d,h),$("#theTable").show())};this.showCsvError=function(){var a=c.loaderErrorTitleCsv;
html=c.loaderErrorBodyCsv;pageManager.showError(a,html)};this.showError=function(b,d){a.data=jQuery.extend({},a.data);a.data.type="csvString";"site"===Wix.Utils.getViewMode()?a.data.csvString=c.loaderErrorTitleViewer+"\n "+c.loaderErrorBodyViewer+"\n":a.data.csvString=b+"\n "+d+"\n";a.tableParams=jQuery.extend({},a.tableParams);a.tableParams.filter=!1;a.tableParams.isError=!0;a.tableParams.sortable=!1;a.tableParams.showHeaderFooter=!0;a.tableParams.alignment="center";dataLoader=new DataLoader;dataLoader.init(a.data,
c,e,f);(new SpreadSheet).init(a.tableParams,g);$("#theTable").show()}};